name: mads lien v2
favicon: null
layout_spectrum: 0.43908651010133326
typography_spectrum: 0.4788435297086835
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.5349457287229598
  lightness: 0.14729683403857052
  saturation: 0.841601338237524
  rhythmicContrast: 0.06166984816081822
purpose: []
